# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  dockerdebugger:
    image: dockerdebugger
    volumes:
      - vidly:/work
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 7000:7000
volumes:
  vidly:
